# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170719_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_topics',
        ),
    ]
