# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_favorite_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_topics',
            field=models.ManyToManyField(to='api.Topic'),
        ),
    ]
