# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170722_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('name',)]),
        ),
    ]
